apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: metric-app
  name: metric-scrape
  namespace: default
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: web
      scrapemetrics: http

